TARGET := iphone:clang:16.5:14.0
ARCHS = arm64

ifdef LUISESTORE_LITE
HELPER_NAME = luisestorehelper_lite
else
HELPER_NAME = luisestorehelper
TARGET_CODESIGN = ../Exploits/fastPathSign/fastPathSign
endif

include $(THEOS)/makefiles/common.mk

TOOL_NAME = $(HELPER_NAME)

$(HELPER_NAME)_FILES = $(wildcard *.m) $(wildcard ../Shared/*.m) $(wildcard ../ChOma/src/*.c)

ifndef LUISESTORE_LITE
$(HELPER_NAME)_FILES += ../Exploits/fastPathSign/src/coretrust_bug.c ../Exploits/fastPathSign/src/codesign.m
$(HELPER_NAME)_CODESIGN_FLAGS = --entitlements entitlements.plist
$(HELPER_NAME)_LDFLAGS = -L../ChOma/external/ios -lcrypto
else
ifeq ($(THEOS_PACKAGE_SCHEME),roothide)
$(HELPER_NAME)_CODESIGN_FLAGS = -Sentitlements-roothide.plist
else
$(HELPER_NAME)_CODESIGN_FLAGS = -Sentitlements.plist
endif
endif
 
$(HELPER_NAME)_CFLAGS = -fobjc-arc -I../Shared $(shell pkg-config --cflags libcrypto) -I../ChOma/src -I../Exploits/fastPathSign/src -I$(shell brew --prefix libarchive)/include

$(HELPER_NAME)_INSTALL_PATH = /usr/local/bin
$(HELPER_NAME)_LIBRARIES = archive
ifeq ($(THEOS_PACKAGE_SCHEME),roothide)
$(HELPER_NAME)_LIBRARIES += roothide
$(HELPER_NAME)_CFLAGS += -DLUISESTORE_ROOTHIDE
endif
$(HELPER_NAME)_FRAMEWORKS = CoreTelephony CoreServices
$(HELPER_NAME)_PRIVATE_FRAMEWORKS = SpringBoardServices BackBoardServices MobileContainerManager FrontBoardServices RunningBoardServices

ifdef LUISESTORE_LITE
$(HELPER_NAME)_CFLAGS += -DLUISESTORE_LITE -DDISABLE_SIGNING=1
endif

include $(THEOS_MAKE_PATH)/tool.mk
